### ISSUE TITLE
Handling long path/file names

### ISSUE THREAD

**Issue by philt2001** [thiscouldbebetter/TarFileExplorer#2] opened 2020-07-16 09:34 UTC
Very useful tool, but I tried to open a tar with file names over 100 characters. These are stored using the LongLink detailed here: https://stackoverflow.com/questions/2078778/what-exactly-is-the-gnu-tar-longlink-trick

Changes would be needed when
- loading
- adding
- deleting

If the extra entry is processed correctly, then saving should be as normal (I think)

**Comment by thiscouldbebetter** [comment] 2020-07-16 20:58
I have reproduced this issue and will attach a .tar file that demonstrates it.
[LongPathNamesTest.zip](https://github.com/thiscouldbebetter/TarFileExplorer/files/4934127/LongPathNamesTest.zip)

**Comment by thiscouldbebetter** [comment] 2020-07-17 02:27
I have added handling of path names longer than 99 characters.  I also fixed the writing of the blanks, zeroes, and nulls in the header fields so that the checksum calculation for the downloaded file matched that of the uploaded one, because otherwise the third-party .tar utility I was using reported the downloaded file as corrupt when I attempted to open it.

I tested with this test plan:

1. Open the TarFileExplorer.html file.
2. Drag the .tar file attached in my previous comment (well, extract it from the .zip first) onto the upload button.
3. Verify that the paths are populated correctly in the interface.
4. Click the Download TAR button and specify the save location in the dialog that appears.  Use the same location as the file uploaded in a previous step.
5. Open the directory containing both the uploaded and downloaded .tar files in a command prompt.
6. In the command prompt, run the "diff" command, followed by the names of the uploaded and downloaded files.
7. Verify that no message is displayed, indicating that the two files are identical.
8. Locate the downloaded file in the File Explorer and attempt to extract it, or to view its contents.  Verify that no error message is displayed.

I will leave this issue open for a few days in case @philt2001 wants to verify the fix independently.  If not, I'll close it.

**Comment by philt2001** [comment] 2020-07-17 21:57
Thanks for your speed doing this. One minor thing, I think you end up adding a null character after the longer file names, which isn't there on the non-modified file names. I can work around this, but there is a slight inconsistency which might want to be resolved. 

Also, I have had a problem when loading some larger files of running out of memory (well chrome stopping before it does), in [byteStream.js](https://github.com/thiscouldbebetter/TarFileExplorer/blob/master/Source/ByteStream.js#L26). I have fixed this by declaring the array to be the size you are going to load
```js
var returnValue = new Array(numberOfBytesToRead);
```

Would that be fixable as well?

Thanks again

**Comment by thiscouldbebetter** [comment] 2020-07-27 21:22
Merged a pull request from philt2001.  Closing this issue.

**Closed by thiscouldbebetter** 2020-07-27 21:22 UTC
